# Copyright 2022 Manna Harbour
# https://github.com/manna-harbour/miryoku

name: 'Build RHS Skeletyl QWERTY VI'
on: workflow_dispatch
jobs:
  build:
    uses: ./.github/workflows/main.yml
    secrets: inherit
    with:
      board: '["nice_nano_v2"]'
      alphas: '["QWERTY"]'
      shield: '["rhs-skeletyl_left","rhs-skeletyl_right"]'
      nav: '["vi"]'

